general:
  world_frame: "odom"
  publish_performance_stats: false

map:
  pruning_period: { seconds: 10.0 }
  visualization_period: { seconds: 10.0 }
  autosave_period: { seconds: -1.0 }
  autosave_path: ""
  data_structure:
    type: "wavelet_octree"
    min_cell_width: { meters: 0.1 }
    max_height: 14

integrator_templates:
  - &vlp16
    integration_method:
      type: "wavelet_integrator"
      min_range: { meters: 1.0 }
      max_range: { meters: 20.0 }
      termination_update_error: 0.1
    projection_model:
      type: "spherical_projector"
      elevation:
        num_cells: 16
        min_angle: { degrees: -15.0 }
        max_angle: { degrees: 15.0 }
      azimuth:
        num_cells: 1740
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: "continuous_beam"
      angle_sigma: { degrees: 0.05 }
      range_sigma: { meters: 0.05 }
      scaling_free: 0.1
      scaling_occupied: 0.2
  - &realsense
    integration_method:
      type: "wavelet_integrator"
      min_range: { meters: 0.5 }
      max_range: { meters: 4.0 }
      termination_update_error: 0.1
    measurement_model:
      type: "continuous_beam"
      angle_sigma: { degrees: 0.04 }
      range_sigma: { meters: 0.04 }
      scaling_free: 0.2
      scaling_occupied: 0.4

integrators:
  - <<: *vlp16
    input:
      type: "pointcloud"
      topic_name: "/velodyne_points"
      reprojected_topic_name: "/velodyne/reprojected"
      topic_queue_length: 3
      max_wait_for_pose: { seconds: 1.0 }
  - <<: *realsense
    input:
      type: "depth_image"
      topic_name: "/depth_camera_front/depth/image_rect_raw"
      image_transport_hints: "compressed"
      reprojected_topic_name: "/depth_camera_front/reprojected"
      depth_scale_factor: 0.001
      topic_queue_length: 3
      max_wait_for_pose: { seconds: 1.0 }
    projection_model:
      type: "pinhole_camera_projector"
      width: 848
      height: 480
      fx: 421.4140625
      cx: 429.63104248046875
      fy: 421.4140625
      cy: 240.18775939941406
  - <<: *realsense
    input:
      type: "depth_image"
      topic_name: "/depth_camera_left/depth/image_rect_raw"
      image_transport_hints: "compressed"
      reprojected_topic_name: "/depth_camera_left/reprojected"
      depth_scale_factor: 0.001
      topic_queue_length: 3
      max_wait_for_pose: { seconds: 1.0 }
    projection_model:
      type: "pinhole_camera_projector"
      width: 848
      height: 480
      fx: 418.9007263183594
      cx: 426.3616027832031
      fy: 418.9007263183594
      cy: 238.4828643798828
  - <<: *realsense
    input:
      type: "depth_image"
      topic_name: "/depth_camera_rear/depth/image_rect_raw"
      image_transport_hints: "compressed"
      reprojected_topic_name: "/depth_camera_rear/reprojected"
      depth_scale_factor: 0.001
      topic_queue_length: 3
      max_wait_for_pose: { seconds: 1.0 }
    projection_model:
      type: "pinhole_camera_projector"
      width: 848
      height: 480
      fx: 424.10040283203125
      cx: 424.1543884277344
      fy: 424.10040283203125
      cy: 238.08590698242188
  - <<: *realsense
    input:
      type: "depth_image"
      topic_name: "/depth_camera_right/depth/image_rect_raw"
      image_transport_hints: "compressed"
      reprojected_topic_name: "/depth_camera_right/reprojected"
      depth_scale_factor: 0.001
      topic_queue_length: 3
      max_wait_for_pose: { seconds: 1.0 }
    projection_model:
      type: "pinhole_camera_projector"
      width: 848
      height: 480
      fx: 423.00006103515625
      cx: 426.5058898925781
      fy: 423.00006103515625
      cy: 234.9111328125
