name: Release Management

on:
  issue_comment:
    types: [ created ]
  pull_request:
    branches: [ main ]

jobs:
  prepare_release_command:
    name: Prepare release commands
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.extract_command.outputs.command }}
    steps:
      - name: Match /prepare-release [major|minor|patch|xx.xx.xx] commands
        id: extract_command
        shell: bash
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          echo Processing comment "$COMMENT"
          version=$(echo $COMMENT | sed -nE "s/^ *\/prepare-release +([0-9]+.[0-9]+.[0-9]+) *$/\1/p")
          if [ -n "${version}" ]; then
            echo command=--version ${version} >> $GITHUB_OUTPUT
            exit
          fi
          bump=$(echo $COMMENT | sed -nE "s/^ *\/prepare-release +(major|minor|patch) *$/\1/p")
          if [ -n "${bump}" ]; then
            echo command=--bump ${bump} >> $GITHUB_OUTPUT
            exit
          fi
          echo command="" >> $GITHUB_OUTPUT

  prepare_release:
    name: Prepare release
    needs: [ prepare_release_command ]
    if: ${{ needs.prepare_release_command.outputs.command }}
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: React to the comment to show it's being processed
        uses: actions/github-script@v6
        with:
          script: |
            octokit.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ github.event.comment.id }},
              content: 'rocket',
            });
      - name: Install dependencies
        shell: bash
        run: apt-get update && apt-get install -q -y --no-install-recommends git python3-catkin-tools
      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Bring branch up to date with main
        run: git merge origin/main
      - name: Bump catkin package version numbers
        shell: bash
        run: python3 tooling/wavemap_utils/scripts/ci_prepare_release.py --non-interactive ${{ needs.prepare_release_command.outputs.command }}
      - name: Push to GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          version_local=$(sed -nE "s/.*<version>(.*)<\/version>.*/\1/p" libraries/wavemap/package.xml)
          git commit -m "Prepare release ${version_local}"
          git push
      - name: Post release note preview as PR comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Preview of release notes will be added here.'
            })

  ready_for_release:
    name: Check if the version exceeds origin main
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3
      - name: Compare local and main version numbers
        shell: bash
        run: |
          version_main=$(curl -s https://raw.githubusercontent.com/ethz-asl/wavemap/main/libraries/wavemap/package.xml | sed -nE "s/.*<version>(.*)<\/version>.*/\1/p")
          version_local=$(sed -nE "s/.*<version>(.*)<\/version>.*/\1/p" libraries/wavemap/package.xml)

          if dpkg --compare-versions $version_main "lt" $version_local; then
            echo "Local version ($version_local) is ahead of origin main ($version_main)"
            exit 0
          else
            echo "Local version ($version_local) lags origin main ($version_main)"
            exit 1
          fi
